apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: phpapp-sqldb
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
  clusterIP: None
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sqldb
  labels:
    app: phpapp-sqldb
    tier: backend
spec:
  selector:
    matchLabels:
      app: phpapp-sqldb
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpapp-sqldb
        tier: backend
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: dbname
        - name: MYSQL_USER
          value: db_user
        - name: MYSQL_PASSWORD
          value: password
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
