apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: phpapp-sqldb
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  labels:
    app: phpapp-sqldb
    tier: frontend
spec:
  selector:
    matchLabels:
      app: phpapp-sqldb
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: phpapp-sqldb
        tier: frontend
    spec:
      containers:
      - name: phpapp-sqldb
        image: <image of your docker container >
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
